### ISSUE TITLE
mvn is not recognized

### ISSUE THREAD

**Issue by omarshiha** [kantega/react-and-spring#4]
'mvn' is not recognized as an internal or external command,
operable program or batch file.
 when trying to mvn clean install ??

**Comment by DavidWestenberger** [comment]
You have to install maven and update your Env varibles.

**Comment by velmuruganvelayutham** [comment]
if you do not have maven installed already, you can use the bash file to execute the maven commands.
.\mvnw clean install

**Comment by oven** [comment]
There is a maven installation guide at https://maven.apache.org/install.html
